// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfdbqrsbhlfzktdvrvvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmZGJxcnNiaGxmemt0ZHZydnZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDEyNzcsImV4cCI6MjA2NTY3NzI3N30.h_tZYfiGWcdck8zS2SuGRuEDm7P8RkTDevGMvGZvZe4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);